name: hoge

on:
  - push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  git-get:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      protect: ${{ steps.get-data.outputs.protect }}
    steps:
      - uses: actions/checkout@v3
      - name: get
        id: get-data
        run: echo "protect=$(bash .github/get.sh)" >> $GITHUB_OUTPUT

  git-echo:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: git-get
    steps:
      - uses: actions/checkout@v3
      - name: echo data
        run: echo ${{ needs.git-get.outputs.protect }}
      - name: json stringify
        env:
          MESSAGE: "ブランチプロテクションの有効化に失敗しました(release) \nProtect: ${{ format('{0}', ${{ toJson(needs.git-get.outputs.protect) }} ) }}"
        run: bash .github/post.sh
